name: Demo workflow
on: workflow_dispatch
jobs:
  print_demo:
    runs-on: ubuntu-latest
    steps:
      - name: Print to console
        run: echo Hello run Action
      - name: Print several lines
        run: |
          echo First line
          echo Second line
          echo Third line
